### ISSUE TITLE
1.13 Client receives internal server error when joining when 1.12 clients are on 1.12 server

### ISSUE THREAD

**Issue by jkorn2324** [Olybear9/MultiVersion-PMMP#22] opened 2019-11-15 00:57 UTC
The report of the log is here: https://pastebin.com/kKLZq4A4

**Comment by Olybear9** [comment] 2019-11-16 23:21
What were you using? this should have been fixed in the commit 66951586df7f5272856bce276e743c89b0a17427

**Comment by jkorn2324** [comment] 2019-11-16 23:33
I was using the latest commit on the dev branch.

**Comment by Olybear9** [comment] 2019-11-19 20:22
I can't reproduce this on the dev branch, are you sure you're using the latest commit?

**Comment by jkorn2324** [comment] 2019-11-19 20:30
I did use the latest commit on the dev branch. It occurs when there is 1.12 players already on the server and a 1.13 client tries to join the server with a legacy skin. The server version is 1.12.

**Comment by Olybear9** [comment] 2019-11-19 21:57
Can reproduce, attempting to fix.

**Comment by Olybear9** [comment] 2019-11-19 22:13
Server buffer does not match 1.13 buffer, need to find something that will be able to patch this.

**Comment by LegoFan48737** [comment] 2019-11-27 17:20
I have this issue, except no one is on the server.
Server is running the latest 1.12 PocketMine, and I'm on 1.13
Error:
[17:16:35] [Server thread/CRITICAL]: Error: "Class 'Bavfalcon9\MultiVersion\Protocols\v1_13_0\types\RuntimeBlockMapping' not found" (EXCEPTION) in "plugins/MultiVersion_v1.0.0.phar/src/Bavfalcon9/MultiVersion/Protocols/v1_13_0/Packets/StartGamePacket" at line 259

**Comment by Lawless1011** [comment] 2019-12-03 12:16
1.12の正式リリース版のSRCを実行しているんですが、サーバーがInternalServerErrorを吐きます。
早期修正をしていただくとありがたいです。
21:12:00] [Server thread/CRITICAL]: Error: "Class 'Bavfalcon9\MultiVersion\Protocols\v1_13_0\types\RuntimeBlockMapping' not found" (EXCEPTION) in "plugins/MultiVersion-PMMP-stable/src/Bavfalcon9/MultiVersion/Protocols/v1_13_0/Packets/StartGamePacket" at line 259

[21:12:00] [Server thread/DEBUG]: #0 src/pocketmine/network/mcpe/protocol/DataPacket(110): Bavfalcon9\MultiVersion\Protocols\v1_13_0\Packets\StartGamePacket->encodePayload()

[21:12:00] [Server thread/DEBUG]: #1 src/pocketmine/network/mcpe/RakLibInterface(235): pocketmine\network\mcpe\protocol\DataPacket->encode()

[21:12:00] [Server thread/DEBUG]: #2 src/pocketmine/Player(3192): pocketmine\network\mcpe\RakLibInterface->putPacket(object Haruki\Annihilation\AnnihilationPlayer, object Bavfalcon9\MultiVersion\Protocols\v1_13_0\Packets\StartGamePacket, boolean , boolean )

[21:12:00] [Server thread/DEBUG]: #3 plugins/MultiVersion-PMMP-stable/src/Bavfalcon9/MultiVersion/Utils/PacketManager(196): pocketmine\Player->sendDataPacket(object Bavfalcon9\MultiVersion\Protocols\v1_13_0\Packets\StartGamePacket)

**Comment by Olybear9** [comment] 2019-12-04 09:17
Solved in: 5c240bd71431d665152e1f4a8993524b4cf76b38 (Temporary)

**Closed** 2019-12-11 01:44 UTC
Labels: 1.13 support, Bug, Can Reproduce, In Progress
